### ISSUE TITLE
Handle double and tripple factorials

### ISSUE THREAD

**Issue by tolik518** [tolik518/factorion-bot#18]
Currently we take only simple factorials into account.

While 3! = 6, 3!! should be treated as (3!)! and it should be 720.

**Comment by LogicalJoe** [comment]
This is wrong, double factorials are the product of every positive integer up to n with the same parity, i.e. `5!! = 1 \* 3 \* 5 == 15 != (5!)!` and can be generalized for multifactorials as demonstrated below.

see https://en.wikipedia.org/wiki/Double_factorial

and https://en.wikipedia.org/wiki/Double_factorial#Generalizations

**Comment by tolik518** [comment]
Oh wow, didn't know that, sounds interesting, thank you @LogicalJoe
