### ISSUE TITLE
Document how to get started 

### ISSUE THREAD

**Issue by tolik518** [tolik518/factorion-bot#3]

**Comment by CodeStrate** [comment]
@tolik518 could assign buddy? I'd like to help out.

**Comment by CodeStrate** [comment]
Should I add instructions for people to create their own user for the bot to listen to (mentions)?

**Comment by tolik518** [comment]
@CodeStrate
The instructions should mostly be aimed towards contributing and developing on the software.

Creating a .env files with a dedicated user should be part of that, yes :)
